### ISSUE TITLE
底层组件独立

### ISSUE THREAD

**Issue by arrowrowe** [stkevintan/nw_musicbox#10]
有兴趣把 `src/model/` 单独做成一个 NPM 包么? 分开底层组件的维护和上层的开发?

**Comment by stkevintan** [comment]
很好的建议。过段时间开坑！

**Comment by arrowrowe** [comment]
点赞

**Comment by stkevintan** [comment]
哈哈，谢谢，以后请大神多多指教~O(∩_∩)O

**Comment by arrowrowe** [comment]
OTL 不敢当

**Comment by arrowrowe** [comment]
See [here](https://github.com/arrowrowe/netease-musicbox-node). (Node v5.2.0)

**Comment by stkevintan** [comment]
Nice! 感谢！

**Comment by arrowrowe** [comment]
用 Wine 开网易云音乐之后没有动力写工具了 orz..... 抱歉

**Comment by stkevintan** [comment]
我也是，毕业了，各种事情。。真是= =

**Comment by arrowrowe** [comment]
patpat...

**Comment by stkevintan** [comment]
233，甲级么？刷刷题就行了～

**Comment by arrowrowe** [comment]
:laughing: 是这个 [pat](http://baike.baidu.com/subview/2461367/17768294.htm). 甲级刚好到我这届不作要求了 (逃

**Comment by stkevintan** [comment]
好吧，get了 = =、
