### ISSUE TITLE
关于代码中得node_module文件夹

### ISSUE THREAD

**Issue by cosven** [stkevintan/nw_musicbox#2]
感觉不需要把node_module文件夹包含在代码源中 ， 不然clone的时候好慢

**Comment by stkevintan** [comment]
包括node_module主要是考虑到那些没有node环境的安装方便的。另外项目依赖也不多，就两个(async和superagent)。可能我的网络环境比较好，clone不要太多时间，终归是我考虑不周，近期会去掉的。

**Comment by rexlevin** [comment]
after you remove node_module, please explain the dependence in you README.md
thank you, i love your app.

**Comment by stkevintan** [comment]
@rexlevin the dependences are all described in package.json and  `npm` will install them automatically.
