### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by junjiangao** [stkevintan/nw_musicbox#7]
使用邮箱登录，[login]http error Error: Bad Request，希望能够修复
其他还好，界面我很喜欢

**Comment by stkevintan** [comment]
@junjiangao  一个小问题，不过这段时间没法碰电脑，所以只能以后再fix了。

**Comment by stkevintan** [comment]
@junjiangao 尝试使用手动方式安装，看看是否可行了。

**Comment by junjiangao** [comment]
重新更新了一下代码，问题解决了
